version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: graph_server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - PYTHONUNBUFFERED=1

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: graph_client
    ports:
      - "4173:4173"
    depends_on:
      - server
